### ISSUE TITLE
What happened to functions occ_to_sp and occ2sp?

### ISSUE THREAD

**Issue by chinchuharris** [ropensci/spocc#186] opened 2018-04-10 00:37 UTC
When I ran the occ_to_sp function in RStudio I got an error message saying that the function could not be found. I'm using spocc version 0.7.0. Are these functions no longer available? I looked through the R documentation for spocc and can't find the functions there either. Do I have download an old version of spocc to run these functions?

**Comment by sckott** [comment] 2018-04-10 00:48
thanks for your question @chinchuharris !

- occ2sp was removed here cause it was a duplicate of occ_to_sp https://github.com/ropensci/spocc/issues/97
- we removed occ_to_sp here https://github.com/ropensci/spocc/commit/4ffaea4 back in june 2015 because we wanted to reduce dependencies in the package since it's already a "heavy package" (that is, lots of other packages are needed for this package to work)

you can still do what those functions did somewhat easily. 

```r
library(sp)
library(maptools)
library(spocc)
occ_to_sp <- function(x, coord_string = "+proj=longlat +datum=WGS84", just_coords = FALSE){
  points <- occ2df(x)
  # remove NA rows
  points <- points[complete.cases(points),]

  # check valid coords
  index <- 1:dim(points)[1]
  index <- index[(points$longitude < 180) & (points$longitude > -180) & !is.na(points$longitude)]
  index <- index[(points$latitude[index] < 90) & (points$latitude[index] > -90) & !is.na(points$latitude[index])]

  spobj <- sp::SpatialPoints(as.matrix(points[index,c('longitude','latitude')]), proj4string = sp::CRS(coord_string))

  sp_df <- sp::SpatialPointsDataFrame(spobj, data = data.frame(points[index,c('name',"prov")]))
  if (just_coords) spobj else sp_df
}


data(wrld_simpl)
plot(wrld_simpl[wrld_simpl$NAME == "United States", ],xlim=c(-70,-60))
out <- occ(query = "Accipiter striatus", from = "gbif")
sp_points <- occ_to_sp(out, just_coords=TRUE)
points(sp_points, col = 2)
```

<img width="716" alt="screen shot 2018-04-09 at 5 47 56 pm" src="https://user-images.githubusercontent.com/577668/38530213-2a80ce74-3c1e-11e8-84b2-c917fba9093a.png">


thoughts?

**Comment by chinchuharris** [comment] 2018-04-10 03:04
Thank you for responding to my question so quickly! @sckott 

Yes, I was able to run occ_to_sp without any errors after using the function you provided above. Thanks again!

**Comment by sckott** [comment] 2018-04-10 20:44
glad it works! i opened a thread on our discussion forum so it's even more findable when people search for it: 

https://discuss.ropensci.org/t/convert-spocc-occ-output-to-a-sp-spatial-class/1135

**Closed by sckott** 2018-04-10 20:44 UTC
